# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: MOA Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  linux:
    uses: ./.github/workflows/dotnet-linux.yml

  windows:
    uses: ./.github/workflows/dotnet-windows.yml

  macos:
    uses: ./.github/workflows/dotnet-macos.yml
